<?php
$message = [
    "All posts"=>"المنشورات",
    "title"=>"العنوان",
    "Blog"=>"المنتدى",
    "show"=>"العرض",
    "edit"=>"التعديل",
    'update'=>"تحديث",
    "delete"=> "الحذف",
    "add new post"=>"إضافه منشور جديد",
    "dir"=>"rtl",
    "logout"=>"تسجيل الخروج",
    'body'=>'الوصف',
    'Add new post'=>'اضافة منشور جديد',
    'Back'=>'رجوع',
    'post'=>'نشر',
    'image'=>'صورة',
    'Previous'=>'السابق',
    'Next'=>'التالي',
    'Actions'=>'الاجراءات',
    'Published At'=>'نشر في',
    'page'=>'الصفحة',
    'page_of'=>'من',
    'Edit post'=>'تعديل المنشور',
    'Login'=>'تسجيل الدخول',
    'Email'=>'البريد الالكتروني ',
    'Password'=>'كلمة المرور',

];